#!/usr/bin/env python3
"""Regenerate topic/difficulty index pages from per-problem README frontmatter.

Reads problems/*/README.md, writes book/by-topic/<topic>.md and
book/by-difficulty/<level>.md, and prints a sidebar fragment for .vitepress/config.mts.
Idempotent — re-run after adding or retagging a problem. Stdlib only.

Frontmatter is the single source of truth; this reads it, never writes it.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PROBLEMS = REPO / "problems"
BOOK = REPO / "book"


def parse_frontmatter(md: Path) -> dict | None:
    text = md.read_text()
    m = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not m:
        return None
    fm: dict = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key, val = key.strip(), val.strip()
        if key == "topics":
            val = [t.strip() for t in val.strip("[]").split(",") if t.strip()]
        elif key == "id":
            val = int(val) if val.isdigit() else None
        fm[key] = val
    return fm


def langs_for(pdir: Path) -> list[str]:
    return sorted({p.suffix[1:] for p in pdir.glob("solution*.*")})


def link_line(p: dict) -> str:
    langs = ", ".join(p["langs"]) or "—"
    lc = f" · [LeetCode]({p['leetcode']})" if p.get("leetcode") else ""
    return f"- [#{p['id']} {p['title']}](/problems/{p['dir']}/) · `{langs}`{lc}"


def write_page(path: Path, title: str, problems: list[dict]) -> None:
    lines = [f"# {title}\n", f"> {len(problems)} problems · generated by `scripts/gen_index.py` — do not edit by hand.\n"]
    for p in sorted(problems, key=lambda p: p["id"]):
        lines.append(link_line(p))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def main() -> None:
    problems = []
    for pdir in sorted(PROBLEMS.iterdir()):
        readme = pdir / "README.md"
        if not pdir.is_dir() or pdir.name.startswith("_") or not readme.exists():
            continue
        fm = parse_frontmatter(readme)
        if not fm or fm.get("id") is None:
            continue
        problems.append({
            "id": fm["id"], "title": fm.get("title", pdir.name), "dir": pdir.name,
            "topics": fm.get("topics") or ["untagged"],
            "difficulty": (fm.get("difficulty") or "").strip() or "Unrated",
            "leetcode": fm.get("leetcode", ""), "langs": langs_for(pdir),
        })

    by_topic: dict[str, list] = {}
    by_diff: dict[str, list] = {}
    for p in problems:
        for t in p["topics"]:
            by_topic.setdefault(t, []).append(p)
        by_diff.setdefault(p["difficulty"], []).append(p)

    # Clean stale generated pages, then rewrite.
    for d in (BOOK / "by-topic", BOOK / "by-difficulty"):
        if d.exists():
            for f in d.glob("*.md"):
                f.unlink()
    for topic, ps in by_topic.items():
        write_page(BOOK / "by-topic" / f"{topic}.md", f"Topic: {topic}", ps)
    for diff, ps in by_diff.items():
        write_page(BOOK / "by-difficulty" / f"{slugify(diff)}.md", f"Difficulty: {diff}", ps)

    print(f"Wrote {len(by_topic)} topic pages, {len(by_diff)} difficulty pages "
          f"({len(problems)} problems).")

    # Emit a sidebar fragment as JSON so .vitepress/config.mts can import it —
    # no manual paste on regen. config.mts spreads this into sidebar[].
    def group(title: str, base: str, keys) -> dict:
        items = []
        for k in sorted(keys):
            page = slugify(k) if base == "by-difficulty" else k
            items.append({"text": f"{k} ({len(by_topic.get(k) or by_diff.get(k))})",
                          "link": f"/book/{base}/{page}"})
        return {"text": title, "collapsed": True, "items": items}

    fragment = [group("Problems by Topic", "by-topic", by_topic),
                group("Problems by Difficulty", "by-difficulty", by_diff)]
    out = REPO / ".vitepress" / "sidebar-problems.json"
    out.write_text(json.dumps(fragment, indent=2) + "\n")
    print(f"Wrote {out.relative_to(REPO)} (imported by config.mts).")


if __name__ == "__main__":
    main()
